CREATE DATABASE planilla;
use planilla;
CREATE TABLE tbl_user(
    userId int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    userFirstName VARCHAR(30),
    userLastName VARCHAR(30),
    userEmail VARCHAR(100),
    userDni VARCHAR(8),
    userStatus  TINYINT NOT NULL,
    userCreated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userUpdated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `userEmail_UNIQUE`(`userEmail`)    
);
-- iden BINARY(16) PRIMARY KEY NOT NULL DEFAULT (UUID_TO_BIN(UUID())), /*ID*/
-- celu CHAR(9) NOT NULL, /*CELULAR*/
-- nomb VARCHAR(30) NOT NULL, /*NOMBRE*/
-- apel VARCHAR(40) NOT NULL, /*APELLIDOS*/
-- dire VARCHAR(100) NOT NULL, /*DIRECCION*/
-- clav CHAR(60) NOT NULL, /*CLAVE*/
-- fere TIMESTAMP DEFAULT CURRENT_TIMESTAMP, /*FECHA DE REGISTRO*/
-- feui TIMESTAMP DEFAULT CURRENT_TIMESTAMP, /*FECHA DE ULTIMO INGRESO*/
-- smse TINYINT NOT NULL DEFAULT 0, /*SMS ENVIADO*/
-- escu TINYINT NOT NULL DEFAULT 0, /*ESTADO DE LA CUENTA: NO CONFIRMADO=0 , CONFIRMADO=1*/
-- codc char(6) NOT NULL,  /*CODIGO DE CONFIRMACION*/
-- latit DECIMAL(10,8) NOT NULL, /*LATITUD*/
-- longi DECIMAL(11,8) NOT NULL, /*LONGITUD*/
-- UNIQUE KEY `celu_UNIQUE`(`celu`)
-- );